### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [9]:
import numpy as np

array = np.random.randint(50,size=10)
print('Média: ',array.mean())
print('Desvio Padrão: ',round(array.std(), 2))


Média:  27.2
Desvio Padrão:  15.55


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [19]:
array = np.random.rand(10)

print('Original: ',array)

for i in range(len(array)):
    if array[i] < 0.5:
        array[i] = np.sqrt(array[i])

print('Raiz: ',array)

Original:  [0.54306588 0.57028448 0.67306019 0.56424022 0.69178215 0.68472442
 0.04973764 0.08509921 0.99123422 0.01806366]
Raiz:  [0.54306588 0.57028448 0.67306019 0.56424022 0.69178215 0.68472442
 0.22301938 0.29171768 0.99123422 0.13440113]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [35]:
matriz = np.random.randint(50, size=[3,3,3])
print(matriz)

for i in range(3):
    for j in range(3):
        print("Maior valor da linha {} coluna {}: {}".format(i, j, matriz[i,j].max()))


[[[38 46 17]
  [21 44 44]
  [40 43  6]]

 [[49 30 23]
  [ 8 30 40]
  [11  7  8]]

 [[48 24 12]
  [38 13 31]
  [ 1 42 23]]]
Maior valor da linha 0 coluna 0: 46
Maior valor da linha 0 coluna 1: 44
Maior valor da linha 0 coluna 2: 43
Maior valor da linha 1 coluna 0: 49
Maior valor da linha 1 coluna 1: 40
Maior valor da linha 1 coluna 2: 11
Maior valor da linha 2 coluna 0: 48
Maior valor da linha 2 coluna 1: 38
Maior valor da linha 2 coluna 2: 42


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [71]:
matriz = np.random.randint(50, size=[5,5])

media = np.mean(matriz, axis=1)

result = matriz - media[:, np.newaxis]

result

array([[ -8. ,  18. ,   0. ,  -9. ,  -1. ],
       [-17.2, -17.2,  -4.2,  24.8,  13.8],
       [ 14.8, -14.2, -18.2,  15.8,   1.8],
       [  5.6, -15.4,   3.6,  14.6,  -8.4],
       [  3.4,   6.4,  10.4,  11.4, -31.6]])

### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [82]:
matriz = np.random.randint(50, size=[4,4])

print(matriz)
print('Média diagonal principal: ',matriz.diagonal().mean())
print('Desvio padão diagonal principal: ',matriz.diagonal().std())

print('Média diagonal secundária: ',np.fliplr(matriz).diagonal().mean())
print('Desvio padão diagonal secundária: ',np.fliplr(matriz).diagonal().std())

[[26 33 21 45]
 [30 44 40  6]
 [29 33  2 13]
 [36 49  5 42]]
Média diagonal principal:  28.5
Desvio padão diagonal principal:  16.815171720800237
Média diagonal secundária:  38.5
Desvio padão diagonal secundária:  4.5
